// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeHandlers 初始化所有Handler
func InitializeHandlers(db *gorm.DB) (*Handlers, error) {
	baseRepository := ProvideBaseRepository(db)
	userRepository := ProvideUserRepository(baseRepository)
	userService := ProvideUserService(userRepository)
	userHandler := ProvideUserHandler(userService)
	handlers := ProvideHandlers(userHandler)
	return handlers, nil
}

// wire.go:

// ProviderSet 所有Provider的集合
var ProviderSet = wire.NewSet(
	ProvideBaseRepository,
	ProvideUserRepository,
	ProvideUserService,
	ProvideUserHandler,
	ProvideHandlers,
)
